apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          resources:
            requests:
              cpu: {{ .Values.backend.resources.requests.cpu | quote }}
              memory: {{ .Values.backend.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.backend.resources.limits.cpu | quote }}
              memory: {{ .Values.backend.resources.limits.memory | quote }}
          livenessProbe:
            httpGet:
              path: {{ .Values.backend.probe.path }}
              port: {{ .Values.backend.port }}
            initialDelaySeconds: {{ .Values.backend.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probe.livenessPeriodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.backend.probe.path }}
              port: {{ .Values.backend.port }}
            initialDelaySeconds: {{ .Values.backend.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.probe.readinessPeriodSeconds }}
