apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secret
          resources:
            requests:
              cpu: {{ .Values.frontend.resources.requests.cpu | quote }}
              memory: {{ .Values.frontend.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.frontend.resources.limits.cpu | quote }}
              memory: {{ .Values.frontend.resources.limits.memory | quote }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.probe.path }}
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: {{ .Values.frontend.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probe.livenessPeriodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.probe.path }}
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: {{ .Values.frontend.probe.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.probe.readinessPeriodSeconds }}
